# Generated by Django 4.2.2 on 2023-06-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('0', 'Em Análise'), ('1', 'Aceita'), ('2', 'Recusada')], default='0', max_length=2)),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
    ]
