# Generated by Django 4.2.2 on 2023-06-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Campo Customizado',
                'verbose_name_plural': 'Campos Customizados',
            },
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='address',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='name',
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='PropostaCustomFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('customfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.propostacustomfield')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.proposta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
